# Generated by Django 4.1.2 on 2022-10-15 19:44

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('popular_dishes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='mark',
            field=models.SmallIntegerField(help_text='Rate this dish from 1 to 5'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_percentage',
            field=models.SmallIntegerField(blank=True),
        ),
    ]
