# Generated by Django 4.1.2 on 2022-10-16 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_rename_category_id_dish_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='mark',
            field=models.SmallIntegerField(help_text='Rate this dish from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
