# Generated by Django 4.1.2 on 2022-10-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_alter_comment_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='discount_percentage',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
