# Generated by Django 4.1.2 on 2022-10-16 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_alter_order_managers_alter_orderdetail_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orderdetail',
            managers=[
            ],
        ),
    ]
