# Generated by Django 4.1.2 on 2022-10-18 21:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0010_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Time commented'),
            preserve_default=False,
        ),
    ]
