# Generated by Django 4.1.2 on 2022-10-19 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0011_comment_data_created'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
