# Generated by Django 4.1.2 on 2022-10-19 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0013_alter_wishlist_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date added'),
            preserve_default=False,
        ),
    ]
