# Generated by Django 4.1.2 on 2022-10-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0014_wishlist_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ship_required',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Estimated shipping time'),
        ),
    ]
